### ISSUE TITLE
Feature: server-rendered index list of all available cocktails

### ISSUE THREAD

**Issue by david-davidson** [redfieldstefan/mixandstones-v2#17]
Our next big challenge is going to be handling interactivity on the client side: getting the webpack build set up ( #12 ), getting flux running ( #14 ), and making sure click handlers and stuff are working ( #10 ). It occurs to me that the perfect test case for almost all that stuff is a cocktails index page with 1.) a text input and 2.) a list of all available cocktails, each with a link to its page: as you type in the input, the list is filtered down in real time.

Before we can make it interactive, we need the base case: a server-rendered index component that simply renders (and links to) all available cocktails. It would follow the same pattern as the server-rendered single cocktail component:
- Middleware the fetches all cocktails and stores them in `res.locals.msData`
- A new route in `client/routes` that associates our route (probably just `/cocktails`?) with a handler component
- A new `cocktails` component that expects an array of cocktails in props and maps over them in `render` to build a cocktail list.

**Comment by david-davidson** [comment]
@redfieldstefan, you have time to snag this one?

**Comment by redfieldstefan** [comment]
On it

**Comment by david-davidson** [comment]
Done!
