### ISSUE TITLE
Repo name should appear canonical

### ISSUE THREAD

**Issue by david-davidson** [redfieldstefan/mixandstones-v2#7]
Since this is now the "true" Mix and Stones, we should rename the old repo something like "msv1" and rename this one either "Mix and Stones" or "Mix and Stones v2"--something a little more verbose, to keep people from ignoring it and looking at its predecessor.

**Comment by redfieldstefan** [comment]
Mega done, renamed as follows:
mixandstones-v1
mixandstones-v2
